title: "David Marsico"
name: "David Marsico"
description: "Research Scientist at CIRES"
location: "Boulder, CO"
email: "david.marsico@colorado.edu"

# This shows up in the sidebar
author:
  name: "David Marsico"
  location: "Boulder, CO"
  email: "david.marsico@colorado.edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:david.marsico@colorado.edu"
